version: '3.1'

networks:
  monitoring:
    driver: overlay

services:
  blog:
    image: 'wordpress'
    ports:
      - 8000:80
    networks:
      - monitoring

  cadvisor:
    image: 'google/cadvisor:latest'
    deploy:
      mode: 'global'
    ports:
      - 8080:8080
    volumes:
      - '/:/rootfs'
      - '/var/run:/var/run'
      - '/sys:/host/sys'
      - '/var/lib/docker:/var/lib/docker'
    networks:
      - monitoring

  prometheus:
    image: 'localhost:5000/prometheus'
    ports:
      - 8081:9090
    networks:
      - monitoring
