version: '3.1'

networks:
  monitoring:
    driver: overlay

services:
  blog:
    image: 'wordpress'
    ports:
      - 8000:80
    networks:
      - monitoring

  cadvisor:
    image: 'google/cadvisor:latest'
    deploy:
      mode: 'global'
    ports:
      - 8080:8080
    volumes:
      - '/:/rootfs'
      - '/var/run:/var/run'
      - '/sys:/host/sys'
      - '/var/lib/docker:/var/lib/docker'
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter
    deploy:
      mode: global
    ports:
      - 8081:9100
    volumes:
      - '/proc:/host/proc'
      - '/sys:/host/sys'
      - '/:/rootfs'
    command:
      - '-collector.procfs=/host/proc'
      - '-collector.sysfs=/host/proc'
      - '-collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - monitoring

  prometheus:
    image: 'localhost:5000/prometheus'
    ports:
      - 8082:9090
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    ports:
      - 8083:3000
    networks:
      - monitoring